[project]
name = "hephaestus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flax>=0.10.2",
    "icecream>=2.1.3",
    "jax>=0.4.35",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "torch>=2.5.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
